### ISSUE TITLE
[Bug] Scan request queue message is too large

### ISSUE THREAD

**Issue by lamaks** [microsoft/accessibility-insights-service#191]
The scan request queue message should be abstracted from Page document.

[Exception][properties - { source: 'scanRequestSender' }] === { VError: Error occurred while executing job: ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>RequestBodyTooLarge</Code><Message>The request body is too large and exceeds the maximum permissible limit.
RequestId:72500c2d-1003-001a-1e51-33cfc4000000
Time:2019-07-05T16:46:24.4987695Z</Message><MaxLimit>65536</MaxLimit></Error>
    at Logger.trackExceptionAny (/mnt/batch/tasks/workitems/scan-req-schedule/job-19/scan-req-sender-task/wd/sender.js:150998:29)
    at ScanRequestEntryPoint.<anonymous> (/mnt/batch/tasks/workitems/scan-req-schedule/job-19/scan-req-sender-task/wd/sender.js:151392:24)
    at Generator.throw (<anonymous>)
    at rejected (/mnt/batch/tasks/workitems/scan-req-schedule/job-19/scan-req-sender-task/wd/sender.js:151350:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  jse_shortmsg: 'Error occurred while executing job',
  jse_cause:
   { Error: ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>RequestBodyTooLarge</Code><Message>The request body is too large and exceeds the maximum permissible limit.
   RequestId:72500c2d-1003-001a-1e51-33cfc4000000
   Time:2019-07-05T16:46:24.4987695Z</Message><MaxLimit>65536</MaxLimit></Error>
       at new RestError (/mnt/batch/tasks/workitems/scan-req-schedule/job-19/scan-req-sender-task/wd/sender.js:20190:28)
       at /mnt/batch/tasks/workitems/scan-req-schedule/job-19/scan-req-sender-task/wd/sender.js:19014:37
       at process._tickCallback (internal/process/next_tick.js:68:7)
     code: undefined,
     statusCode: 413,

**Comment by manishsat** [comment]
@flyingUnderTheRadar Fixed it.
