### ISSUE TITLE
[Bug] Crawling regression between 1.7.0 and 2.1.1

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-service#2445]
## Describe the bug

https://github.com/microsoft/accessibility-insights-action/pull/1718 moves from ai-scan 1.7.0 to 2.1.1. There were some formatting changes that we had to adjust, but we found a regression in the crawler. A simplified view of our web site is as follows (this omits the content of the `linked1` and `linked2` folders):

```
/
  /linked1
    ... omitted for brevity
  /linked2
    ... omitted for brevity
  /unlinked
    index.html
    other.html
```

`/unlinked/index.html` contains a relative reference to `other.html`. We pass `/unlinked` as the `inputUrl` parameter, and when the crawler scans `/unlinked/index.html`, it mishandles the relative reference. Instead of resolving to `/unlinked/other.html`, it resolves to `/other.html`. This page does not exist, so it throws a 404 error.

This is a regression from version 1.7.0, which properly resolved the relative reference.

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service

## To Reproduce

1. Clone https://github.com/microsoft/accessibility-insights-action/tree/DaveTryon/investigate-scan-failure (this is a branched from https://github.com/microsoft/accessibility-insights-action/pull/1718 with other e2e tests stripped out)
2. yarn install
3. yarn build
4. yarn test:e2e to see the failure

## Expected behavior

Relative references should be respected

## Log files

Here is a snipped of the log file from 1.7.0 -- note that it correctly adds `/unlinked/other` in the 7th line:
```
Processing page http://localhost:39983/unlinked/
Discovered 1 links on page http://localhost:39983/unlinked/
Found 1 accessibility issues on page http://localhost:39983/unlinked/
Processing page http://localhost:39983/
Discovered 2 links on page http://localhost:39983/
Found 4 accessibility issues on page http://localhost:39983/
Processing page http://localhost:39983/unlinked/other.html
Discovered 1 links on page http://localhost:39983/unlinked/other.html
Processing page http://localhost:39983/linked1/
Discovered 2 links on page http://localhost:39983/linked1/
Processing page http://localhost:39983/linked2/
Discovered 1 links on page http://localhost:39983/linked2/
Processing page http://localhost:39983/linked1/inner-page.html
Discovered 1 links on page http://localhost:39983/linked1/inner-page.html
Found 2 accessibility issues on page http://localhost:39983/linked1/inner-page.html
```

Here is a redacted snippet of the log file from 2.1.1 -- notice that when it navigates to `other.html` (the 12th line of the log), it omits the relative path, which leads to the 404 error

```
	Started local web server. Url: http://localhost:39983 Root directory: .\dev\website-root
	Scanning URL http://localhost:39983/
	Starting accessibility scanning of URL http://localhost:39983/
	Chrome app executable: default (bundled with task)
	PuppeteerCrawler: Starting the crawl
	Navigate page to URL. {"requestId":"YyyhPUuyWkCR16t","url":"http://localhost:39983/unlinked"}
	Processing loaded page. {"url":"http://localhost:39983/unlinked/"}
	Enqueued 1 new links. {"url":"http://localhost:39983/unlinked/"}
	Navigate page to URL. {"requestId":"popY6iV78AF6eEp","url":"http://localhost:39983/"}
	Processing loaded page. {"url":"http://localhost:39983/"}
	Enqueued 2 new links. {"url":"http://localhost:39983/"}
	Navigate page to URL. {"requestId":"GVLPeycWSA4Sl7a","url":"http://localhost:39983/other.html"}
	Navigate page to URL. {"requestId":"AJPJtWeTrYIC3Yj","url":"http://localhost:39983/linked1/"}
	Processing loaded page. {"url":"http://localhost:39983/linked1/"}
	Enqueued 2 new links. {"url":"http://localhost:39983/linked1/"}
	Navigate page to URL. {"requestId":"L0ltIGnYj228UtL","url":"http://localhost:39983/linked2/"}
	Processing loaded page. {"url":"http://localhost:39983/linked2/"}
	Enqueued 1 new links. {"url":"http://localhost:39983/linked2/"}
	Navigate page to URL. {"requestId":"dVGCZv5Y0khqsaf","url":"http://localhost:39983/linked1/inner-page.html"}
	Processing loaded page. {"url":"http://localhost:39983/linked1/inner-page.html"}
	Enqueued 1 new links. {"url":"http://localhost:39983/linked1/inner-page.html"}
	PuppeteerCrawler: All requests from the queue have been processed, the crawler will shut down.
	ErrorWithCause: An error occurred while scanning website page: http://localhost:39983/other.html
		at Logger.trackExceptionAny (.\packages\ado-extension\dist\pkg\index.js:185541:29)
		at Scanner.logAndTrackScanningException (.\packages\ado-extension\dist\pkg\index.js:186804:21)
		at .\packages\ado-extension\dist\pkg\index.js:186735:30
		at Array.forEach (<anonymous>)
		at Scanner.<anonymous> (.\packages\ado-extension\dist\pkg\index.js:186734:47)
		at Generator.next (<anonymous>)
		at fulfilled (.\packages\ado-extension\dist\pkg\index.js:186637:58)
	caused by: Error: '{' +
	  "  errorType: 'HttpErrorCode'," +
	  '  statusCode: 404,' +
	  "  statusText: 'Not Found'," +
	  "  message: 'Page returned an unsuccessful response code'," +
	  "  stack: 'Error\' +" +
	  "    '    at PageResponseProcessor.getResponseError (.\packages\ado-extension\dist\pkg\ode_modules\accessibility-insights-scan\dist\index.js:8070:40)\' +" +
	  "    '    at PageNavigationHooks.postNavigation (.\packages\ado-extension\dist\pkg\ode_modules\accessibility-insights-scan\dist\index.js:7784:58)\' +" +
	  "    '    at PageNavigator.navigatePage (.\packages\ado-extension\dist\pkg\ode_modules\accessibility-insights-scan\dist\index.js:7906:73)\' +" +
	  "    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\' +" +
	  "    '    at async PuppeteerCrawler.PageProcessorBase.requestHandler [as userProvidedRequestHandler] (.\packages\ado-extension\dist\pkg\ode_modules\accessibility-insights-scan\dist\index.js:4309:28)\' +" +
	  "    '    at async wrap (.\packages\ado-extension\dist\pkg\ode_modules\@apify\timeout\index.js:52:21)'" +
	"}"
```

**Comment by lamaks** [comment]
The issue with action E2E test. The line in [ado-extension.test.ts](https://github.com/microsoft/accessibility-insights-action/blob/c28a9f7ac132f8939aefe7eaeee8d114d4b92014/packages/ado-extension/e2e/ado-extension.test.ts#L98) should look like below:

```
inputUrls: 'http://localhost:39983/unlinked/'
```

The crawler distinguish between web page and web folder. The URL trailing forward slash denote a web folder that is expected by the E2E test.

**Comment by DaveTryon** [comment]
Thanks, @lamaks! That worked. I opened #2450 for another issue that I found when adding the change that you suggested. I'll close this issue out since we have a way forward.
